from .Producto import Producto as ProductoResource
from .Producto import Productos as ProductosResource
from .Compra import Compras as ComprasResource
from .Compra import Compra as CompraResource
from .Compra import CompraFecha as CompraFechaResource
from .Usuario import Usuario as UsuarioResource
from .Usuario import Usuarios as UsuariosResource
from .Inventario import Inventarios as InventariosResource
from .Local import Locals as LocalsResource
from .Venta import Ventas as VentasResource
from .DetalleVenta import DetalleVenta as DetalleVentaResource
from .DetalleVenta import DetalleVentas as DetalleVentasResource
from .Intercambio import Intercambio as IntercambioResource